spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sectors
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    change-log: db/changelog-master.yaml
