INSERT INTO sector (id, name, parent) values (1,	'Manufacturing', null);
INSERT INTO sector (id, name, parent) values (19,	'-Construction materials', 1);
INSERT INTO sector (id, name, parent) values (18,	'-Electronics and Optics', 1);
INSERT INTO sector (id, name, parent) values (6,	'-Food and Beverage', 1);
INSERT INTO sector (id, name, parent) values (342,	'--Bakery &amp; confectionery products', 6);
INSERT INTO sector (id, name, parent) values (43,	'--Beverages', 6);
INSERT INTO sector (id, name, parent) values (42,	'--Fish &amp; fish products', 6);
INSERT INTO sector (id, name, parent) values (40,	'--Meat &amp; meat products', 6);
INSERT INTO sector (id, name, parent) values (39,	'--Milk &amp; dairy products', 6);
INSERT INTO sector (id, name, parent) values (437,	'--Other', 6);
INSERT INTO sector (id, name, parent) values (378,	'--Sweets &amp; snack food', 6);
INSERT INTO sector (id, name, parent) values (13,	'-Furniture', 1);
INSERT INTO sector (id, name, parent) values (389,	'--Bathroom/sauna', 13);
INSERT INTO sector (id, name, parent) values (385,	'--Bedroom', 13);
INSERT INTO sector (id, name, parent) values (390,	'--Children’s room', 13);
INSERT INTO sector (id, name, parent) values (98,	'--Kitchen', 13);
INSERT INTO sector (id, name, parent) values (101,	'--Living room', 13);
INSERT INTO sector (id, name, parent) values (392,	'--Office', 13);
INSERT INTO sector (id, name, parent) values (394,	'--Other (Furniture)', 13);
INSERT INTO sector (id, name, parent) values (341,	'--Outdoor', 13);
INSERT INTO sector (id, name, parent) values (99,	'--Project furniture', 13);
INSERT INTO sector (id, name, parent) values (12,	'-Machinery', 1);
INSERT INTO sector (id, name, parent) values (94,	'--Machinery components', 12);
INSERT INTO sector (id, name, parent) values (91,	'--Machinery equipment/tools', 12);
INSERT INTO sector (id, name, parent) values (224,	'--Manufacture of machinery', 12);
INSERT INTO sector (id, name, parent) values (97,	'--Maritime', 12);
INSERT INTO sector (id, name, parent) values (271,	'---Aluminium and steel workboats', 97);
INSERT INTO sector (id, name, parent) values (269,	'---Boat/Yacht building', 97);
INSERT INTO sector (id, name, parent) values (230,	'---Ship repair and conversion', 97);
INSERT INTO sector (id, name, parent) values (93,	'--Metal structures', 12);
INSERT INTO sector (id, name, parent) values (508,	'--Other', 12);
INSERT INTO sector (id, name, parent) values (227,	'--Repair and maintenance service', 12);
INSERT INTO sector (id, name, parent) values (11,	'-Metalworking', 1);
INSERT INTO sector (id, name, parent) values (67,	'--Construction of metal structures', 11);
INSERT INTO sector (id, name, parent) values (263,	'--Houses and buildings', 11);
INSERT INTO sector (id, name, parent) values (267,	'--Metal products', 11);
INSERT INTO sector (id, name, parent) values (542,	'--Metal works', 11);
INSERT INTO sector (id, name, parent) values (75,	'---CNC-machining', 542);
INSERT INTO sector (id, name, parent) values (62,	'---Forgings, Fasteners', 542);
INSERT INTO sector (id, name, parent) values (69,	'---Gas, Plasma, Laser cutting', 542);
INSERT INTO sector (id, name, parent) values (66,	'---MIG, TIG, Aluminum welding', 542);
INSERT INTO sector (id, name, parent) values (9,	'-Plastic and Rubber', 1);
INSERT INTO sector (id, name, parent) values (54,	'--Packaging', 9);
INSERT INTO sector (id, name, parent) values (556,	'--Plastic goods', 9);
INSERT INTO sector (id, name, parent) values (559,	'--Plastic processing technology', 9);
INSERT INTO sector (id, name, parent) values (55,	'---Blowing', 559);
INSERT INTO sector (id, name, parent) values (57,	'---Moulding', 559);
INSERT INTO sector (id, name, parent) values (53,	'---Plastics welding and processing', 559);
INSERT INTO sector (id, name, parent) values (560,	'--Plastic profiles', 9);
INSERT INTO sector (id, name, parent) values (5,	'-Printing', 1);
INSERT INTO sector (id, name, parent) values (148,	'--Advertising', 5);
INSERT INTO sector (id, name, parent) values (150,	'--Book/Periodicals printing', 5);
INSERT INTO sector (id, name, parent) values (145,	'--Labelling and packaging printing', 5);
INSERT INTO sector (id, name, parent) values (7,	'-Textile and Clothing', 1);
INSERT INTO sector (id, name, parent) values (44,	'--Clothing', 7);
INSERT INTO sector (id, name, parent) values (45,	'--Textile', 7);
INSERT INTO sector (id, name, parent) values (8,	'-Wood', 1);
INSERT INTO sector (id, name, parent) values (337,	'--Other (Wood)', 8);
INSERT INTO sector (id, name, parent) values (51,	'--Wooden building materials', 8);
INSERT INTO sector (id, name, parent) values (47,	'--Wooden houses', 8);
INSERT INTO sector (id, name, parent) values (3,	'Other', null);
INSERT INTO sector (id, name, parent) values (37,	'-Creative industries', 3);
INSERT INTO sector (id, name, parent) values (29,	'-Energy technology', 3);
INSERT INTO sector (id, name, parent) values (33,	'-Environment', 3);
INSERT INTO sector (id, name, parent) values (2,	'Service', null);
INSERT INTO sector (id, name, parent) values (25,	'-Business services', 2);
INSERT INTO sector (id, name, parent) values (35,	'-Engineering', 2);
INSERT INTO sector (id, name, parent) values (28,	'-Information Technology and Telecommunications', 2);
INSERT INTO sector (id, name, parent) values (581,	'--Data processing, Web portals, E-marketing', 28);
INSERT INTO sector (id, name, parent) values (576,	'--Programming, Consultancy', 28);
INSERT INTO sector (id, name, parent) values (121,	'--Software, Hardware', 28);
INSERT INTO sector (id, name, parent) values (122,	'--Telecommunications', 28);
INSERT INTO sector (id, name, parent) values (22,	'-Tourism', 2);
INSERT INTO sector (id, name, parent) values (141,	'-Translation services', 2);
INSERT INTO sector (id, name, parent) values (21,	'-Transport and Logistics', 2);
INSERT INTO sector (id, name, parent) values (111,	'--Air', 21);
INSERT INTO sector (id, name, parent) values (114,	'--Rail', 21);
INSERT INTO sector (id, name, parent) values (112,	'--Road', 21);
INSERT INTO sector (id, name, parent) values (113,	'--Water', 21);
